config/routes.rb
Rails.application.routes.draw do

  resources :wizards

  resources :accounts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "contacts#new", :as => "signup"

  get "contacts/:id/verification" => "contacts#verification", :as => "verification"
  post "contacts/:id/verify" => "contacts#verify", as: "verify"

  resources :chats
  resources :sessions

  post "incoming" => "commands#incoming"
  # post "/help" => "commands#help", as: "help"
  # post "/invite" => "commands#invite", as: "invite"
  # post "/search" => "commands#search", as: "search"
  # post "/friends" => "commands#friends", as: "friends"
  # post "/spin" => "commands#spin", as: "spin"

  get 'commands/outgoing'

  post "/send_message" => "chats#send_message", as: "send_message"
  post "/send_image" => "chats#send_image", as: "send_image"

  get "contacts/:auth_token/friends" => "contacts#friends", :as => "friends"

  match 'bots/updates', to: 'telegram#handle_updates', as: 'handle_updates', via: 'post'

  resources :contacts

  root to: 'home#index'
  devise_for :users
end

app/models/wizard.rb
class Wizard < ActiveRecord::Base
  belongs_to :account
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :set_wizard, only: [:show, :edit, :update, :destroy]

  # GET /wizards
  # GET /wizards.json
  def index
    @wizards = Wizard.all
  end

  # GET /wizards/1
  # GET /wizards/1.json
  def show
  end

  # GET /wizards/new
  def new
    @wizard = Wizard.new
  end

  # GET /wizards/1/edit
  def edit
  end

  # POST /wizards
  # POST /wizards.json
  def create
    @wizard = Wizard.new(wizard_params)

    respond_to do |format|
      if @wizard.save
        format.html { redirect_to @wizard, notice: 'Wizard was successfully created.' }
        format.json { render :show, status: :created, location: @wizard }
      else
        format.html { render :new }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wizards/1
  # PATCH/PUT /wizards/1.json
  def update
    respond_to do |format|
      if @wizard.update(wizard_params)
        format.html { redirect_to @wizard, notice: 'Wizard was successfully updated.' }
        format.json { render :show, status: :ok, location: @wizard }
      else
        format.html { render :edit }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizards/1
  # DELETE /wizards/1.json
  def destroy
    @wizard.destroy
    respond_to do |format|
      format.html { redirect_to wizards_url, notice: 'Wizard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wizard
      @wizard = Wizard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wizard_params
      params.require(:wizard).permit(:name, :account_id)
    end
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/wizards/_form.html.haml
= form_for @wizard do |f|
  - if @wizard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@wizard.errors.count, "error")} prohibited this wizard from being saved:"
      %ul
        - @wizard.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :account
    = f.text_field :account
  .actions
    = f.submit 'Save'

app/views/wizards/edit.html.haml
%h1 Editing wizard

= render 'form'

= link_to 'Show', @wizard
\|
= link_to 'Back', wizards_path

app/views/wizards/index.html.haml
%h1 Listing wizards

%table
  %thead
    %tr
      %th Name
      %th Account
      %th
      %th
      %th

  %tbody
    - @wizards.each do |wizard|
      %tr
        %td= wizard.name
        %td= wizard.account
        %td= link_to 'Show', wizard
        %td= link_to 'Edit', edit_wizard_path(wizard)
        %td= link_to 'Destroy', wizard, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Wizard', new_wizard_path

app/views/wizards/new.html.haml
%h1 New wizard

= render 'form'

= link_to 'Back', wizards_path

app/views/wizards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @wizard.name
%p
  %b Account:
  = @wizard.account

= link_to 'Edit', edit_wizard_path(@wizard)
\|
= link_to 'Back', wizards_path