config/routes.rb
Rails.application.routes.draw do

  resources :wizards

  resources :accounts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "contacts#new", :as => "signup"

  get "contacts/:id/verification" => "contacts#verification", :as => "verification"
  post "contacts/:id/verify" => "contacts#verify", as: "verify"

  resources :chats
  resources :sessions

  post "incoming" => "commands#incoming"
  # post "/help" => "commands#help", as: "help"
  # post "/invite" => "commands#invite", as: "invite"
  # post "/search" => "commands#search", as: "search"
  # post "/friends" => "commands#friends", as: "friends"
  # post "/spin" => "commands#spin", as: "spin"

  get 'commands/outgoing'

  post "/send_message" => "chats#send_message", as: "send_message"
  post "/send_image" => "chats#send_image", as: "send_image"

  get "contacts/:auth_token/friends" => "contacts#friends", :as => "friends"

  match 'bots/updates', to: 'telegram#handle_updates', as: 'handle_updates', via: 'post'

  resources :contacts

  root to: 'home#index'
  devise_for :users
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :users
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :setup, :account_type, :email)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :setup
    = f.check_box :setup
  .field
    = f.label :account_type
    = f.text_field :account_type
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %thead
    %tr
      %th Name
      %th Setup
      %th Account type
      %th Email
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td= account.setup
        %td= account.account_type
        %td= account.email
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Setup:
  = @account.setup
%p
  %b Account type:
  = @account.account_type
%p
  %b Email:
  = @account.email

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path